-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_527_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    add_ln316 : IN STD_LOGIC_VECTOR (31 downto 0);
    t_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    t_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    t_12 : IN STD_LOGIC_VECTOR (63 downto 0);
    t_sroa_52_7_lcssa43107120147163 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (31 downto 0);
    use_fwd_3109119149161 : IN STD_LOGIC_VECTOR (0 downto 0);
    sel_tmp6 : IN STD_LOGIC_VECTOR (0 downto 0);
    phi_ln59 : IN STD_LOGIC_VECTOR (9 downto 0);
    active_depth_3 : IN STD_LOGIC_VECTOR (8 downto 0);
    sp_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    sp_4_out_ap_vld : OUT STD_LOGIC;
    t_44_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    t_44_out_ap_vld : OUT STD_LOGIC;
    t_43_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    t_43_out_ap_vld : OUT STD_LOGIC;
    t_42_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    t_42_out_ap_vld : OUT STD_LOGIC;
    t_41_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    t_41_out_ap_vld : OUT STD_LOGIC;
    f_surv_tokens_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_1_ce0 : OUT STD_LOGIC;
    f_surv_tokens_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    f_surv_tokens_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_0_ce0 : OUT STD_LOGIC;
    f_surv_tokens_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_surv_tokens_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_surv_tokens_1_ce0 : OUT STD_LOGIC;
    b_surv_tokens_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_surv_tokens_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_surv_tokens_0_ce0 : OUT STD_LOGIC;
    b_surv_tokens_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    frontier_stack_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    frontier_stack_ce0 : OUT STD_LOGIC;
    frontier_stack_we0 : OUT STD_LOGIC;
    frontier_stack_d0 : OUT STD_LOGIC_VECTOR (19 downto 0) );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_527_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv64_13 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln527_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln527_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln532_fu_335_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln532_reg_614 : STD_LOGIC_VECTOR (0 downto 0);
    signal sp_load_1_reg_641 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln538_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln538_reg_646 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln61_fu_453_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln61_reg_650 : STD_LOGIC_VECTOR (9 downto 0);
    signal sp_1_fu_458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sp_1_reg_655 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln532_fu_349_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln540_fu_503_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idx_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_idx_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln527_fu_329_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_1_fu_114 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_4_fu_464_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_2_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_8_fu_512_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_3_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_7_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sp_fu_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal lshr_ln9_fu_339_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln532_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln533_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln536_fu_379_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln536_1_fu_383_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal and_ln532_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln536_2_fu_395_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln536_3_fu_399_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln533_fu_387_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln533_1_fu_403_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_418_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal tok_fu_411_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_445_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln552_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fd_bb_slbb_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fd_bb_slbb_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    idx_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln527_fu_323_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    idx_fu_106 <= add_ln527_fu_329_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    idx_fu_106 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    sp_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    sp_fu_126 <= add_ln316;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln538_fu_428_p2 = ap_const_lv1_1))) then 
                    sp_fu_126 <= sp_1_fu_458_p2;
                end if;
            end if; 
        end if;
    end process;

    t_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_1_fu_114 <= t_12;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln538_fu_428_p2 = ap_const_lv1_1))) then 
                    t_1_fu_114 <= t_4_fu_464_p2;
                end if;
            end if; 
        end if;
    end process;

    t_2_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    t_2_fu_118 <= t_6;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln538_reg_646 = ap_const_lv1_1))) then 
                    t_2_fu_118 <= t_8_fu_512_p3;
                end if;
            end if; 
        end if;
    end process;

    t_3_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_3_fu_122 <= t_5;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln538_fu_428_p2 = ap_const_lv1_1))) then 
                    t_3_fu_122 <= t_7_fu_470_p2;
                end if;
            end if; 
        end if;
    end process;

    t_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_110 <= t_sroa_52_7_lcssa43107120147163;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln538_fu_428_p2 = ap_const_lv1_0))) then 
                    t_fu_110 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln527_reg_610 <= icmp_ln527_fu_323_p2;
                icmp_ln538_reg_646 <= icmp_ln538_fu_428_p2;
                sp_load_1_reg_641 <= sp_fu_126;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln538_fu_428_p2 = ap_const_lv1_1))) then
                or_ln61_reg_650 <= or_ln61_fu_453_p2;
                sp_1_reg_655 <= sp_1_fu_458_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln527_fu_323_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln532_reg_614 <= trunc_ln532_fu_335_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln527_fu_329_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_idx_1) + unsigned(ap_const_lv32_1));
    and_ln532_fu_370_p2 <= (xor_ln532_fu_365_p2 and use_fwd_3109119149161);
    and_ln533_fu_375_p2 <= (trunc_ln532_reg_614 and sel_tmp6);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln527_fu_323_p2)
    begin
        if (((icmp_ln527_fu_323_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_idx_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, idx_fu_106, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_idx_1 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_idx_1 <= idx_fu_106;
        end if; 
    end process;

    b_surv_tokens_0_address0 <= zext_ln532_fu_349_p1(8 - 1 downto 0);

    b_surv_tokens_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_surv_tokens_0_ce0 <= ap_const_logic_1;
        else 
            b_surv_tokens_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    b_surv_tokens_1_address0 <= zext_ln532_fu_349_p1(8 - 1 downto 0);

    b_surv_tokens_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_surv_tokens_1_ce0 <= ap_const_logic_1;
        else 
            b_surv_tokens_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_0_address0 <= zext_ln532_fu_349_p1(8 - 1 downto 0);

    f_surv_tokens_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            f_surv_tokens_0_ce0 <= ap_const_logic_1;
        else 
            f_surv_tokens_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_1_address0 <= zext_ln532_fu_349_p1(8 - 1 downto 0);

    f_surv_tokens_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            f_surv_tokens_1_ce0 <= ap_const_logic_1;
        else 
            f_surv_tokens_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    frontier_stack_address0 <= zext_ln540_fu_503_p1(11 - 1 downto 0);

    frontier_stack_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            frontier_stack_ce0 <= ap_const_logic_1;
        else 
            frontier_stack_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    frontier_stack_d0 <= ((active_depth_3 & ap_const_lv1_0) & or_ln61_reg_650);

    frontier_stack_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln538_reg_646)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln538_reg_646 = ap_const_lv1_1))) then 
            frontier_stack_we0 <= ap_const_logic_1;
        else 
            frontier_stack_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln527_fu_323_p2 <= "1" when (ap_sig_allocacmp_idx_1 = empty) else "0";
    icmp_ln538_fu_428_p2 <= "1" when (signed(tmp_1_fu_418_p4) < signed(ap_const_lv21_1)) else "0";
    icmp_ln552_fu_507_p2 <= "1" when (unsigned(sp_1_reg_655) > unsigned(t_2_fu_118)) else "0";
    lshr_ln9_fu_339_p4 <= ap_sig_allocacmp_idx_1(8 downto 1);
    or_ln61_fu_453_p2 <= (tmp_s_fu_445_p3 or phi_ln59);
    select_ln533_1_fu_403_p3 <= 
        trunc_ln536_2_fu_395_p1 when (and_ln532_fu_370_p2(0) = '1') else 
        trunc_ln536_3_fu_399_p1;
    select_ln533_fu_387_p3 <= 
        trunc_ln536_fu_379_p1 when (and_ln533_fu_375_p2(0) = '1') else 
        trunc_ln536_1_fu_383_p1;
    sp_1_fu_458_p2 <= std_logic_vector(unsigned(sp_fu_126) + unsigned(ap_const_lv32_1));
    sp_4_out <= sp_fu_126;

    sp_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln527_reg_610)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln527_reg_610 = ap_const_lv1_1))) then 
            sp_4_out_ap_vld <= ap_const_logic_1;
        else 
            sp_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_41_out <= t_fu_110;

    t_41_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln527_reg_610)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln527_reg_610 = ap_const_lv1_1))) then 
            t_41_out_ap_vld <= ap_const_logic_1;
        else 
            t_41_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_42_out <= t_1_fu_114;

    t_42_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln527_reg_610)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln527_reg_610 = ap_const_lv1_1))) then 
            t_42_out_ap_vld <= ap_const_logic_1;
        else 
            t_42_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_43_out <= t_2_fu_118;

    t_43_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln527_reg_610)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln527_reg_610 = ap_const_lv1_1))) then 
            t_43_out_ap_vld <= ap_const_logic_1;
        else 
            t_43_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_44_out <= t_3_fu_122;

    t_44_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln527_reg_610)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln527_reg_610 = ap_const_lv1_1))) then 
            t_44_out_ap_vld <= ap_const_logic_1;
        else 
            t_44_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_4_fu_464_p2 <= std_logic_vector(unsigned(t_1_fu_114) + unsigned(ap_const_lv64_13));
    t_7_fu_470_p2 <= std_logic_vector(unsigned(t_3_fu_122) + unsigned(ap_const_lv32_1));
    t_8_fu_512_p3 <= 
        sp_1_reg_655 when (icmp_ln552_fu_507_p2(0) = '1') else 
        t_2_fu_118;
    tmp_1_fu_418_p4 <= sp_fu_126(31 downto 11);
    tmp_s_fu_445_p3 <= (ap_const_lv1_0 & tok_fu_411_p3);
    tok_fu_411_p3 <= 
        select_ln533_fu_387_p3 when (trunc_ln532_reg_614(0) = '1') else 
        select_ln533_1_fu_403_p3;
    trunc_ln532_fu_335_p1 <= ap_sig_allocacmp_idx_1(1 - 1 downto 0);
    trunc_ln536_1_fu_383_p1 <= f_surv_tokens_1_q0(9 - 1 downto 0);
    trunc_ln536_2_fu_395_p1 <= f_surv_tokens_0_q0(9 - 1 downto 0);
    trunc_ln536_3_fu_399_p1 <= b_surv_tokens_0_q0(9 - 1 downto 0);
    trunc_ln536_fu_379_p1 <= b_surv_tokens_1_q0(9 - 1 downto 0);
    xor_ln532_fu_365_p2 <= (trunc_ln532_reg_614 xor ap_const_lv1_1);
    zext_ln532_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln9_fu_339_p4),64));
    zext_ln540_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sp_load_1_reg_641),64));
end behav;
