-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_332_11 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m : IN STD_LOGIC_VECTOR (31 downto 0);
    add_ln335 : IN STD_LOGIC_VECTOR (13 downto 0);
    p_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_ce0 : OUT STD_LOGIC;
    p_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cfwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cfwd_ce0 : OUT STD_LOGIC;
    cur_cfwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cbwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cbwd_ce0 : OUT STD_LOGIC;
    cur_cbwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    rem_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce0 : OUT STD_LOGIC;
    rem_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    lb_f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    lb_f_out_ap_vld : OUT STD_LOGIC;
    c_run_f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_run_f_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_332_11 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln332_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln332_reg_334 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln332_reg_334_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln332_reg_334_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln332_1_fu_184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln332_1_reg_338 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln332_1_reg_338_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal pj_reg_354 : STD_LOGIC_VECTOR (15 downto 0);
    signal cf_parent_reg_359 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_run_f_1_fu_232_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_run_f_1_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal rem_excl_fu_256_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rem_excl_reg_379 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_fu_278_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_reg_384 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln335_1_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal c_run_f_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lb_f_fu_64 : STD_LOGIC_VECTOR (31 downto 0);
    signal lb_f_1_fu_291_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_68 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_k_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln332_fu_178_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln332_fu_168_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln335_fu_189_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln335_1_fu_193_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln341_fu_212_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln341_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal base_fu_221_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln345_fu_229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln348_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln348_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln349_fu_250_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln353_fu_269_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln353_fu_273_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln355_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fd_bb_slbb_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fd_bb_slbb_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    c_run_f_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    c_run_f_fu_60 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    c_run_f_fu_60 <= c_run_f_1_fu_232_p2;
                end if;
            end if; 
        end if;
    end process;

    k_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln332_fu_172_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_68 <= add_ln332_fu_178_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_68 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    lb_f_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lb_f_fu_64 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    lb_f_fu_64 <= lb_f_1_fu_291_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cf_parent_reg_359 <= cur_cfwd_q0;
                icmp_ln332_reg_334 <= icmp_ln332_fu_172_p2;
                icmp_ln332_reg_334_pp0_iter1_reg <= icmp_ln332_reg_334;
                pj_reg_354 <= p_q0;
                    zext_ln332_1_reg_338_pp0_iter1_reg(5 downto 0) <= zext_ln332_1_reg_338(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                c_run_f_1_reg_374 <= c_run_f_1_fu_232_p2;
                icmp_ln332_reg_334_pp0_iter2_reg <= icmp_ln332_reg_334_pp0_iter1_reg;
                rem_excl_reg_379 <= rem_excl_fu_256_p3;
                v_reg_384 <= v_fu_278_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln332_fu_172_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln332_1_reg_338(5 downto 0) <= zext_ln332_1_fu_184_p1(5 downto 0);
            end if;
        end if;
    end process;
    zext_ln332_1_reg_338(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln332_1_reg_338_pp0_iter1_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln332_fu_178_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_2) + unsigned(ap_const_lv6_1));
    add_ln335_1_fu_193_p2 <= std_logic_vector(unsigned(add_ln335) + unsigned(zext_ln335_fu_189_p1));
    add_ln353_fu_273_p2 <= std_logic_vector(unsigned(rem_excl_reg_379) + unsigned(zext_ln353_fu_269_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln332_fu_172_p2)
    begin
        if (((icmp_ln332_fu_172_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_2 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_k_2 <= k_fu_68;
        end if; 
    end process;

    base_fu_221_p3 <= 
        zext_ln341_fu_212_p1 when (icmp_ln341_fu_215_p2(0) = '1') else 
        c_run_f_fu_60;
    c_run_f_1_fu_232_p2 <= std_logic_vector(unsigned(base_fu_221_p3) + unsigned(zext_ln345_fu_229_p1));
    c_run_f_out <= c_run_f_fu_60;

    c_run_f_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln332_reg_334_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln332_reg_334_pp0_iter2_reg = ap_const_lv1_1))) then 
            c_run_f_out_ap_vld <= ap_const_logic_1;
        else 
            c_run_f_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cur_cbwd_address0 <= zext_ln332_1_reg_338_pp0_iter1_reg(5 - 1 downto 0);

    cur_cbwd_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            cur_cbwd_ce0 <= ap_const_logic_1;
        else 
            cur_cbwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    cur_cfwd_address0 <= zext_ln332_1_fu_184_p1(5 - 1 downto 0);

    cur_cfwd_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cur_cfwd_ce0 <= ap_const_logic_1;
        else 
            cur_cfwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln332_fu_172_p2 <= "1" when (zext_ln332_fu_168_p1 = m) else "0";
    icmp_ln341_fu_215_p2 <= "1" when (unsigned(zext_ln341_fu_212_p1) > unsigned(c_run_f_fu_60)) else "0";
    icmp_ln348_fu_238_p2 <= "1" when (unsigned(rem_r_q0) < unsigned(zext_ln345_fu_229_p1)) else "0";
    icmp_ln355_fu_286_p2 <= "1" when (unsigned(v_reg_384) > unsigned(lb_f_fu_64)) else "0";
    lb_f_1_fu_291_p3 <= 
        v_reg_384 when (icmp_ln355_fu_286_p2(0) = '1') else 
        lb_f_fu_64;
    lb_f_out <= lb_f_fu_64;

    lb_f_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln332_reg_334_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln332_reg_334_pp0_iter2_reg = ap_const_lv1_1))) then 
            lb_f_out_ap_vld <= ap_const_logic_1;
        else 
            lb_f_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_address0 <= zext_ln335_1_fu_199_p1(14 - 1 downto 0);

    p_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ce0 <= ap_const_logic_1;
        else 
            p_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    rem_excl_fu_256_p3 <= 
        sub_ln349_fu_250_p2 when (xor_ln348_fu_244_p2(0) = '1') else 
        ap_const_lv32_0;
    rem_r_address0 <= zext_ln332_1_reg_338(5 - 1 downto 0);

    rem_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rem_r_ce0 <= ap_const_logic_1;
        else 
            rem_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln349_fu_250_p2 <= std_logic_vector(unsigned(rem_r_q0) - unsigned(zext_ln345_fu_229_p1));
    v_fu_278_p2 <= std_logic_vector(unsigned(add_ln353_fu_273_p2) + unsigned(c_run_f_1_reg_374));
    xor_ln348_fu_244_p2 <= (icmp_ln348_fu_238_p2 xor ap_const_lv1_1);
    zext_ln332_1_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_2),64));
    zext_ln332_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_2),32));
    zext_ln335_1_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln335_1_fu_193_p2),64));
    zext_ln335_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_2),14));
    zext_ln341_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cf_parent_reg_359),32));
    zext_ln345_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pj_reg_354),32));
    zext_ln353_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cur_cbwd_q0),32));
end behav;
