-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_278_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    add_ln167 : IN STD_LOGIC_VECTOR (30 downto 0);
    t_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln258 : IN STD_LOGIC_VECTOR (13 downto 0);
    add_ln260 : IN STD_LOGIC_VECTOR (13 downto 0);
    p_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_ce0 : OUT STD_LOGIC;
    p_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cbwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cbwd_ce0 : OUT STD_LOGIC;
    cur_cbwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cbwd_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cbwd_ce1 : OUT STD_LOGIC;
    cur_cbwd_we1 : OUT STD_LOGIC;
    cur_cbwd_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    rem_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce0 : OUT STD_LOGIC;
    rem_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    rem_r_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce1 : OUT STD_LOGIC;
    rem_r_we1 : OUT STD_LOGIC;
    rem_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    t_20_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    t_20_out_ap_vld : OUT STD_LOGIC;
    restore_vec_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    restore_vec_ce0 : OUT STD_LOGIC;
    restore_vec_we0 : OUT STD_LOGIC;
    restore_vec_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_278_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_364_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln282_fu_217_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln282_reg_368 : STD_LOGIC_VECTOR (13 downto 0);
    signal cur_cbwd_addr_reg_378 : STD_LOGIC_VECTOR (4 downto 0);
    signal cur_cbwd_addr_reg_378_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal cur_cbwd_addr_reg_378_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal rem_addr_reg_384 : STD_LOGIC_VECTOR (4 downto 0);
    signal rem_addr_reg_384_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal old_cb_reg_390 : STD_LOGIC_VECTOR (15 downto 0);
    signal pj_reg_395 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_reg_401 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln29_fu_299_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln29_reg_406 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln284_fu_229_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln278_fu_207_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln282_fu_245_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_9_fu_317_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal next_fu_78 : STD_LOGIC_VECTOR (31 downto 0);
    signal next_1_fu_283_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_82 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln167_cast_fu_177_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_k_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln278_fu_234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln282_fu_213_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln284_fu_223_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln286_fu_252_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln289_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln289_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal base_fu_271_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln293_fu_279_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln22_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_34 : BOOLEAN;
    signal ap_enable_state1_pp0_iter0_stage0 : BOOLEAN;
    signal ap_enable_operation_41 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_enable_operation_64 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_enable_operation_44 : BOOLEAN;
    signal ap_enable_operation_47 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_enable_operation_49 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fd_bb_slbb_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fd_bb_slbb_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    k_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((tmp_fu_199_p3 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    k_fu_82 <= add_ln278_fu_234_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_82 <= add_ln167_cast_fu_177_p1;
                end if;
            end if; 
        end if;
    end process;

    next_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    next_fu_78 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    next_fu_78 <= next_1_fu_283_p2;
                end if;
            end if; 
        end if;
    end process;

    t_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    t_fu_74 <= t_13;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    t_fu_74 <= t_9_fu_317_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_199_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln282_reg_368 <= add_ln282_fu_217_p2;
                cur_cbwd_addr_reg_378 <= zext_ln278_fu_207_p1(5 - 1 downto 0);
                rem_addr_reg_384 <= zext_ln278_fu_207_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln29_reg_406 <= add_ln29_fu_299_p2;
                cur_cbwd_addr_reg_378_pp0_iter2_reg <= cur_cbwd_addr_reg_378_pp0_iter1_reg;
                tmp_2_reg_401 <= next_1_fu_283_p2(31 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cur_cbwd_addr_reg_378_pp0_iter1_reg <= cur_cbwd_addr_reg_378;
                pj_reg_395 <= p_q0;
                rem_addr_reg_384_pp0_iter1_reg <= rem_addr_reg_384;
                tmp_reg_364 <= ap_sig_allocacmp_k_3(31 downto 31);
                tmp_reg_364_pp0_iter1_reg <= tmp_reg_364;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                old_cb_reg_390 <= cur_cbwd_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln167_cast_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln167),32));
    add_ln278_fu_234_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_3) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln282_fu_217_p2 <= std_logic_vector(unsigned(zext_ln258) + unsigned(trunc_ln282_fu_213_p1));
    add_ln284_fu_223_p2 <= std_logic_vector(unsigned(add_ln260) + unsigned(trunc_ln282_fu_213_p1));
    add_ln29_fu_299_p2 <= std_logic_vector(unsigned(pj_reg_395) + unsigned(trunc_ln293_fu_279_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, tmp_fu_199_p3, ap_start_int)
    begin
        if (((tmp_fu_199_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_34_assign_proc : process(tmp_fu_199_p3)
    begin
                ap_enable_operation_34 <= (tmp_fu_199_p3 = ap_const_lv1_0);
    end process;

        ap_enable_operation_41 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_44 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_47 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_49 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_64 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state1_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_start_int)
    begin
                ap_enable_state1_pp0_iter0_stage0 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_82, add_ln167_cast_fu_177_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_3 <= add_ln167_cast_fu_177_p1;
        else 
            ap_sig_allocacmp_k_3 <= k_fu_82;
        end if; 
    end process;

    base_fu_271_p3 <= 
        zext_ln289_fu_262_p1 when (icmp_ln289_fu_265_p2(0) = '1') else 
        next_fu_78;
    cur_cbwd_address0 <= zext_ln278_fu_207_p1(5 - 1 downto 0);
    cur_cbwd_address1 <= cur_cbwd_addr_reg_378_pp0_iter2_reg;

    cur_cbwd_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cur_cbwd_ce0 <= ap_const_logic_1;
        else 
            cur_cbwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    cur_cbwd_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            cur_cbwd_ce1 <= ap_const_logic_1;
        else 
            cur_cbwd_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    cur_cbwd_d1 <= 
        ap_const_lv16_FFFF when (icmp_ln22_fu_312_p2(0) = '1') else 
        add_ln29_reg_406;

    cur_cbwd_we1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            cur_cbwd_we1 <= ap_const_logic_1;
        else 
            cur_cbwd_we1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln22_fu_312_p2 <= "0" when (tmp_2_reg_401 = ap_const_lv16_0) else "1";
    icmp_ln289_fu_265_p2 <= "1" when (unsigned(zext_ln289_fu_262_p1) > unsigned(next_fu_78)) else "0";
    next_1_fu_283_p2 <= std_logic_vector(unsigned(base_fu_271_p3) + unsigned(zext_ln286_fu_252_p1));
    p_address0 <= zext_ln284_fu_229_p1(14 - 1 downto 0);

    p_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ce0 <= ap_const_logic_1;
        else 
            p_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    rem_r_address0 <= rem_addr_reg_384;
    rem_r_address1 <= rem_addr_reg_384_pp0_iter1_reg;

    rem_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rem_r_ce0 <= ap_const_logic_1;
        else 
            rem_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    rem_r_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            rem_r_ce1 <= ap_const_logic_1;
        else 
            rem_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    rem_r_d1 <= std_logic_vector(unsigned(rem_r_q0) - unsigned(zext_ln286_fu_252_p1));

    rem_r_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            rem_r_we1 <= ap_const_logic_1;
        else 
            rem_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    restore_vec_address0 <= zext_ln282_fu_245_p1(14 - 1 downto 0);

    restore_vec_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            restore_vec_ce0 <= ap_const_logic_1;
        else 
            restore_vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    restore_vec_d0 <= cur_cbwd_q0;

    restore_vec_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            restore_vec_we0 <= ap_const_logic_1;
        else 
            restore_vec_we0 <= ap_const_logic_0;
        end if; 
    end process;

    t_20_out <= t_fu_74;

    t_20_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, tmp_reg_364_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_364_pp0_iter1_reg = ap_const_lv1_1))) then 
            t_20_out_ap_vld <= ap_const_logic_1;
        else 
            t_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t_9_fu_317_p3 <= 
        ap_const_lv8_1 when (icmp_ln22_fu_312_p2(0) = '1') else 
        t_fu_74;
    tmp_fu_199_p3 <= ap_sig_allocacmp_k_3(31 downto 31);
    trunc_ln282_fu_213_p1 <= ap_sig_allocacmp_k_3(14 - 1 downto 0);
    trunc_ln293_fu_279_p1 <= base_fu_271_p3(16 - 1 downto 0);
    zext_ln278_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_3),64));
    zext_ln282_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln282_reg_368),64));
    zext_ln284_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln284_fu_223_p2),64));
    zext_ln286_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pj_reg_395),32));
    zext_ln289_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(old_cb_reg_390),32));
end behav;
