-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_385_12 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln167 : IN STD_LOGIC_VECTOR (31 downto 0);
    add_ln335 : IN STD_LOGIC_VECTOR (13 downto 0);
    p_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_ce0 : OUT STD_LOGIC;
    p_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cfwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cfwd_ce0 : OUT STD_LOGIC;
    cur_cfwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cbwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cbwd_ce0 : OUT STD_LOGIC;
    cur_cbwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    rem_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce0 : OUT STD_LOGIC;
    rem_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    lb_b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    lb_b_out_ap_vld : OUT STD_LOGIC;
    c_run_b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_run_b_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_385_12 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_183_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal k_1_reg_332 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_1_reg_332_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_343_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_343_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pj_reg_352 : STD_LOGIC_VECTOR (15 downto 0);
    signal cb_parent_reg_357 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_run_b_1_fu_225_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_run_b_1_reg_372 : STD_LOGIC_VECTOR (31 downto 0);
    signal rem_excl_fu_249_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rem_excl_reg_377 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_reg_382 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln388_fu_178_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal c_run_b_fu_56 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lb_b_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal lb_b_1_fu_284_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_64 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln385_fu_191_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln167_cast_fu_146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln388_fu_169_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln388_fu_173_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln394_fu_205_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln394_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal base_fu_214_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln398_fu_222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln401_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln401_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln402_fu_243_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln406_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln406_fu_266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln408_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fd_bb_slbb_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fd_bb_slbb_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    c_run_b_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    c_run_b_fu_56 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    c_run_b_fu_56 <= c_run_b_1_fu_225_p2;
                end if;
            end if; 
        end if;
    end process;

    k_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_64 <= sext_ln167_cast_fu_146_p1;
                elsif (((tmp_fu_183_p3 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    k_fu_64 <= add_ln385_fu_191_p2;
                end if;
            end if; 
        end if;
    end process;

    lb_b_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lb_b_fu_60 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    lb_b_fu_60 <= lb_b_1_fu_284_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                k_1_reg_332 <= k_fu_64;
                tmp_reg_343 <= k_fu_64(63 downto 63);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                c_run_b_1_reg_372 <= c_run_b_1_fu_225_p2;
                cb_parent_reg_357 <= cur_cbwd_q0;
                k_1_reg_332_pp0_iter2_reg <= k_1_reg_332;
                pj_reg_352 <= p_q0;
                rem_excl_reg_377 <= rem_excl_fu_249_p3;
                tmp_reg_343_pp0_iter2_reg <= tmp_reg_343;
                tmp_reg_343_pp0_iter3_reg <= tmp_reg_343_pp0_iter2_reg;
                v_reg_382 <= v_fu_271_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln385_fu_191_p2 <= std_logic_vector(unsigned(k_fu_64) + unsigned(ap_const_lv64_FFFFFFFFFFFFFFFF));
    add_ln388_fu_173_p2 <= std_logic_vector(unsigned(add_ln335) + unsigned(trunc_ln388_fu_169_p1));
    add_ln406_fu_266_p2 <= std_logic_vector(unsigned(c_run_b_1_reg_372) + unsigned(zext_ln406_fu_262_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, tmp_fu_183_p3)
    begin
        if (((tmp_fu_183_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    base_fu_214_p3 <= 
        zext_ln394_fu_205_p1 when (icmp_ln394_fu_208_p2(0) = '1') else 
        c_run_b_fu_56;
    c_run_b_1_fu_225_p2 <= std_logic_vector(unsigned(base_fu_214_p3) + unsigned(zext_ln398_fu_222_p1));
    c_run_b_out <= c_run_b_fu_56;

    c_run_b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, tmp_reg_343_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_343_pp0_iter3_reg = ap_const_lv1_1))) then 
            c_run_b_out_ap_vld <= ap_const_logic_1;
        else 
            c_run_b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cur_cbwd_address0 <= k_fu_64(5 - 1 downto 0);

    cur_cbwd_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cur_cbwd_ce0 <= ap_const_logic_1;
        else 
            cur_cbwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    cur_cfwd_address0 <= k_1_reg_332_pp0_iter2_reg(5 - 1 downto 0);

    cur_cfwd_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            cur_cfwd_ce0 <= ap_const_logic_1;
        else 
            cur_cfwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln394_fu_208_p2 <= "1" when (unsigned(zext_ln394_fu_205_p1) > unsigned(c_run_b_fu_56)) else "0";
    icmp_ln401_fu_231_p2 <= "1" when (unsigned(rem_r_q0) < unsigned(zext_ln398_fu_222_p1)) else "0";
    icmp_ln408_fu_279_p2 <= "1" when (unsigned(v_reg_382) > unsigned(lb_b_fu_60)) else "0";
    lb_b_1_fu_284_p3 <= 
        v_reg_382 when (icmp_ln408_fu_279_p2(0) = '1') else 
        lb_b_fu_60;
    lb_b_out <= lb_b_fu_60;

    lb_b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, tmp_reg_343_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_343_pp0_iter3_reg = ap_const_lv1_1))) then 
            lb_b_out_ap_vld <= ap_const_logic_1;
        else 
            lb_b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_address0 <= zext_ln388_fu_178_p1(14 - 1 downto 0);

    p_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ce0 <= ap_const_logic_1;
        else 
            p_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    rem_excl_fu_249_p3 <= 
        sub_ln402_fu_243_p2 when (xor_ln401_fu_237_p2(0) = '1') else 
        ap_const_lv32_0;
    rem_r_address0 <= k_1_reg_332(5 - 1 downto 0);

    rem_r_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            rem_r_ce0 <= ap_const_logic_1;
        else 
            rem_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln167_cast_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln167),64));

    sub_ln402_fu_243_p2 <= std_logic_vector(unsigned(rem_r_q0) - unsigned(zext_ln398_fu_222_p1));
    tmp_fu_183_p3 <= k_fu_64(63 downto 63);
    trunc_ln388_fu_169_p1 <= k_fu_64(14 - 1 downto 0);
    v_fu_271_p2 <= std_logic_vector(unsigned(add_ln406_fu_266_p2) + unsigned(rem_excl_reg_377));
    xor_ln401_fu_237_p2 <= (icmp_ln401_fu_231_p2 xor ap_const_lv1_1);
    zext_ln388_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln388_fu_173_p2),64));
    zext_ln394_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cb_parent_reg_357),32));
    zext_ln398_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pj_reg_352),32));
    zext_ln406_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cur_cfwd_q0),32));
end behav;
