-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_485_14 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln478 : IN STD_LOGIC_VECTOR (30 downto 0);
    key_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    pos_1_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    pos_1_out_ap_vld : OUT STD_LOGIC;
    f_surv_tokens_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_1_ce0 : OUT STD_LOGIC;
    f_surv_tokens_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    f_surv_tokens_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_1_ce1 : OUT STD_LOGIC;
    f_surv_tokens_1_we1 : OUT STD_LOGIC;
    f_surv_tokens_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_surv_tokens_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_0_ce0 : OUT STD_LOGIC;
    f_surv_tokens_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    f_surv_tokens_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    f_surv_tokens_0_ce1 : OUT STD_LOGIC;
    f_surv_tokens_0_we1 : OUT STD_LOGIC;
    f_surv_tokens_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_485_14 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal pos_reg_224 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln486_fu_135_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln486_reg_230 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_reg_236 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln487_fu_157_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln490_fu_196_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln487_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_1_fu_50 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln493_fu_202_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln478_cast_fu_123_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln487_fu_163_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln487_fu_166_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln5_fu_147_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln490_fu_181_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln8_fu_186_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    pos_1_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                pos_1_fu_50 <= zext_ln478_cast_fu_123_p1;
            elsif (((icmp_ln487_fu_176_p2 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                pos_1_fu_50 <= add_ln493_fu_202_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                pos_reg_224 <= pos_1_fu_50;
                tmp_reg_236 <= pos_1_fu_50(63 downto 63);
                trunc_ln486_reg_230 <= trunc_ln486_fu_135_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_reg_236, ap_CS_fsm_state3, icmp_ln487_fu_176_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln487_fu_176_p2 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((tmp_reg_236 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln490_fu_181_p2 <= std_logic_vector(unsigned(trunc_ln486_reg_230) + unsigned(ap_const_lv9_1));
    add_ln493_fu_202_p2 <= std_logic_vector(unsigned(pos_reg_224) + unsigned(ap_const_lv64_FFFFFFFFFFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_0_address0 <= zext_ln487_fu_157_p1(8 - 1 downto 0);
    f_surv_tokens_0_address1 <= zext_ln490_fu_196_p1(8 - 1 downto 0);

    f_surv_tokens_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            f_surv_tokens_0_ce0 <= ap_const_logic_1;
        else 
            f_surv_tokens_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    f_surv_tokens_0_ce1_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            f_surv_tokens_0_ce1 <= ap_const_logic_1;
        else 
            f_surv_tokens_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_0_d1 <= select_ln487_fu_166_p3;

    f_surv_tokens_0_we1_assign_proc : process(tmp_reg_236, ap_CS_fsm_state3, icmp_ln487_fu_176_p2, trunc_ln487_fu_163_p1)
    begin
        if (((icmp_ln487_fu_176_p2 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (trunc_ln487_fu_163_p1 = ap_const_lv1_1))) then 
            f_surv_tokens_0_we1 <= ap_const_logic_1;
        else 
            f_surv_tokens_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_1_address0 <= zext_ln487_fu_157_p1(8 - 1 downto 0);
    f_surv_tokens_1_address1 <= zext_ln490_fu_196_p1(8 - 1 downto 0);

    f_surv_tokens_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            f_surv_tokens_1_ce0 <= ap_const_logic_1;
        else 
            f_surv_tokens_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    f_surv_tokens_1_ce1_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            f_surv_tokens_1_ce1 <= ap_const_logic_1;
        else 
            f_surv_tokens_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    f_surv_tokens_1_d1 <= select_ln487_fu_166_p3;

    f_surv_tokens_1_we1_assign_proc : process(tmp_reg_236, ap_CS_fsm_state3, icmp_ln487_fu_176_p2, trunc_ln487_fu_163_p1)
    begin
        if (((icmp_ln487_fu_176_p2 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (trunc_ln487_fu_163_p1 = ap_const_lv1_0))) then 
            f_surv_tokens_1_we1 <= ap_const_logic_1;
        else 
            f_surv_tokens_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln487_fu_176_p2 <= "1" when (unsigned(select_ln487_fu_166_p3) < unsigned(key_1)) else "0";
    lshr_ln5_fu_147_p4 <= pos_1_fu_50(8 downto 1);
    lshr_ln8_fu_186_p4 <= add_ln490_fu_181_p2(8 downto 1);
    pos_1_out <= trunc_ln486_reg_230;

    pos_1_out_ap_vld_assign_proc : process(tmp_reg_236, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((tmp_reg_236 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            pos_1_out_ap_vld <= ap_const_logic_1;
        else 
            pos_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln487_fu_166_p3 <= 
        f_surv_tokens_1_q0 when (trunc_ln487_fu_163_p1(0) = '1') else 
        f_surv_tokens_0_q0;
    trunc_ln486_fu_135_p1 <= pos_1_fu_50(9 - 1 downto 0);
    trunc_ln487_fu_163_p1 <= pos_reg_224(1 - 1 downto 0);
    zext_ln478_cast_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln478),64));
    zext_ln487_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_147_p4),64));
    zext_ln490_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln8_fu_186_p4),64));
end behav;
