-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_254_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    t_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    m : IN STD_LOGIC_VECTOR (30 downto 0);
    zext_ln258 : IN STD_LOGIC_VECTOR (13 downto 0);
    add_ln260 : IN STD_LOGIC_VECTOR (13 downto 0);
    p_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_ce0 : OUT STD_LOGIC;
    p_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cfwd_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cfwd_ce0 : OUT STD_LOGIC;
    cur_cfwd_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cur_cfwd_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    cur_cfwd_ce1 : OUT STD_LOGIC;
    cur_cfwd_we1 : OUT STD_LOGIC;
    cur_cfwd_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    rem_r_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce0 : OUT STD_LOGIC;
    rem_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    rem_r_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    rem_r_ce1 : OUT STD_LOGIC;
    rem_r_we1 : OUT STD_LOGIC;
    rem_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    t_18_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    t_18_out_ap_vld : OUT STD_LOGIC;
    restore_vec_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    restore_vec_ce0 : OUT STD_LOGIC;
    restore_vec_we0 : OUT STD_LOGIC;
    restore_vec_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_254_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln254_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln254_reg_366 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln254_reg_366_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln258_fu_225_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln258_reg_370 : STD_LOGIC_VECTOR (13 downto 0);
    signal cur_cfwd_addr_reg_380 : STD_LOGIC_VECTOR (4 downto 0);
    signal cur_cfwd_addr_reg_380_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal cur_cfwd_addr_reg_380_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal rem_addr_reg_386 : STD_LOGIC_VECTOR (4 downto 0);
    signal rem_addr_reg_386_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal old_cf_reg_392 : STD_LOGIC_VECTOR (15 downto 0);
    signal pj_reg_397 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_403 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln29_fu_301_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln29_reg_408 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln260_fu_237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln254_fu_215_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_2_fu_247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_78 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_10_fu_319_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal prev_fu_82 : STD_LOGIC_VECTOR (31 downto 0);
    signal prev_1_fu_285_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_3_fu_86 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_k : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln254_fu_209_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln254_1_fu_199_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln258_1_fu_221_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln260_1_fu_231_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln262_fu_254_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln265_fu_264_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln265_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal base_fu_273_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln269_fu_281_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln22_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_35 : BOOLEAN;
    signal ap_enable_state1_pp0_iter0_stage0 : BOOLEAN;
    signal ap_enable_operation_41 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_enable_operation_64 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_enable_operation_44 : BOOLEAN;
    signal ap_enable_operation_47 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_enable_operation_49 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fd_bb_slbb_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fd_bb_slbb_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    k_3_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln254_fu_203_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    k_3_fu_86 <= add_ln254_fu_209_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_3_fu_86 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    prev_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    prev_fu_82 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    prev_fu_82 <= prev_1_fu_285_p2;
                end if;
            end if; 
        end if;
    end process;

    t_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    t_fu_78 <= t_13;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    t_fu_78 <= t_10_fu_319_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln254_fu_203_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln258_reg_370 <= add_ln258_fu_225_p2;
                cur_cfwd_addr_reg_380 <= zext_ln254_fu_215_p1(5 - 1 downto 0);
                rem_addr_reg_386 <= zext_ln254_fu_215_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln29_reg_408 <= add_ln29_fu_301_p2;
                cur_cfwd_addr_reg_380_pp0_iter2_reg <= cur_cfwd_addr_reg_380_pp0_iter1_reg;
                tmp_reg_403 <= prev_1_fu_285_p2(31 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cur_cfwd_addr_reg_380_pp0_iter1_reg <= cur_cfwd_addr_reg_380;
                icmp_ln254_reg_366 <= icmp_ln254_fu_203_p2;
                icmp_ln254_reg_366_pp0_iter1_reg <= icmp_ln254_reg_366;
                pj_reg_397 <= p_q0;
                rem_addr_reg_386_pp0_iter1_reg <= rem_addr_reg_386;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                old_cf_reg_392 <= cur_cfwd_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln254_fu_209_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k) + unsigned(ap_const_lv6_1));
    add_ln258_fu_225_p2 <= std_logic_vector(unsigned(zext_ln258) + unsigned(zext_ln258_1_fu_221_p1));
    add_ln260_1_fu_231_p2 <= std_logic_vector(unsigned(add_ln260) + unsigned(zext_ln258_1_fu_221_p1));
    add_ln29_fu_301_p2 <= std_logic_vector(unsigned(pj_reg_397) + unsigned(trunc_ln269_fu_281_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln254_fu_203_p2, ap_start_int)
    begin
        if (((icmp_ln254_fu_203_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_35_assign_proc : process(icmp_ln254_fu_203_p2)
    begin
                ap_enable_operation_35 <= (icmp_ln254_fu_203_p2 = ap_const_lv1_0);
    end process;

        ap_enable_operation_41 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_44 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_47 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_49 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_64 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state1_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_start_int)
    begin
                ap_enable_state1_pp0_iter0_stage0 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_3_fu_86)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_k <= k_3_fu_86;
        end if; 
    end process;

    base_fu_273_p3 <= 
        zext_ln265_fu_264_p1 when (icmp_ln265_fu_267_p2(0) = '1') else 
        prev_fu_82;
    cur_cfwd_address0 <= zext_ln254_fu_215_p1(5 - 1 downto 0);
    cur_cfwd_address1 <= cur_cfwd_addr_reg_380_pp0_iter2_reg;

    cur_cfwd_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cur_cfwd_ce0 <= ap_const_logic_1;
        else 
            cur_cfwd_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    cur_cfwd_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            cur_cfwd_ce1 <= ap_const_logic_1;
        else 
            cur_cfwd_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    cur_cfwd_d1 <= 
        ap_const_lv16_FFFF when (icmp_ln22_fu_314_p2(0) = '1') else 
        add_ln29_reg_408;

    cur_cfwd_we1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            cur_cfwd_we1 <= ap_const_logic_1;
        else 
            cur_cfwd_we1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln22_fu_314_p2 <= "0" when (tmp_reg_403 = ap_const_lv16_0) else "1";
    icmp_ln254_fu_203_p2 <= "1" when (zext_ln254_1_fu_199_p1 = m) else "0";
    icmp_ln265_fu_267_p2 <= "1" when (unsigned(zext_ln265_fu_264_p1) > unsigned(prev_fu_82)) else "0";
    p_address0 <= zext_ln260_fu_237_p1(14 - 1 downto 0);

    p_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ce0 <= ap_const_logic_1;
        else 
            p_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    prev_1_fu_285_p2 <= std_logic_vector(unsigned(base_fu_273_p3) + unsigned(zext_ln262_fu_254_p1));
    rem_r_address0 <= rem_addr_reg_386;
    rem_r_address1 <= rem_addr_reg_386_pp0_iter1_reg;

    rem_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rem_r_ce0 <= ap_const_logic_1;
        else 
            rem_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    rem_r_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            rem_r_ce1 <= ap_const_logic_1;
        else 
            rem_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    rem_r_d1 <= std_logic_vector(unsigned(rem_r_q0) - unsigned(zext_ln262_fu_254_p1));

    rem_r_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            rem_r_we1 <= ap_const_logic_1;
        else 
            rem_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    restore_vec_address0 <= zext_ln258_2_fu_247_p1(14 - 1 downto 0);

    restore_vec_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            restore_vec_ce0 <= ap_const_logic_1;
        else 
            restore_vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    restore_vec_d0 <= cur_cfwd_q0;

    restore_vec_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            restore_vec_we0 <= ap_const_logic_1;
        else 
            restore_vec_we0 <= ap_const_logic_0;
        end if; 
    end process;

    t_10_fu_319_p3 <= 
        ap_const_lv8_1 when (icmp_ln22_fu_314_p2(0) = '1') else 
        t_fu_78;
    t_18_out <= t_fu_78;

    t_18_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln254_reg_366_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln254_reg_366_pp0_iter1_reg = ap_const_lv1_1))) then 
            t_18_out_ap_vld <= ap_const_logic_1;
        else 
            t_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln269_fu_281_p1 <= base_fu_273_p3(16 - 1 downto 0);
    zext_ln254_1_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k),31));
    zext_ln254_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k),64));
    zext_ln258_1_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k),14));
    zext_ln258_2_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln258_reg_370),64));
    zext_ln260_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln260_1_fu_231_p2),64));
    zext_ln262_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pj_reg_397),32));
    zext_ln265_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(old_cf_reg_392),32));
end behav;
