// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_254_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_13,
        m,
        zext_ln258,
        add_ln260,
        p_address0,
        p_ce0,
        p_q0,
        cur_cfwd_address0,
        cur_cfwd_ce0,
        cur_cfwd_q0,
        cur_cfwd_address1,
        cur_cfwd_ce1,
        cur_cfwd_we1,
        cur_cfwd_d1,
        rem_r_address0,
        rem_r_ce0,
        rem_r_q0,
        rem_r_address1,
        rem_r_ce1,
        rem_r_we1,
        rem_r_d1,
        t_18_out,
        t_18_out_ap_vld,
        restore_vec_address0,
        restore_vec_ce0,
        restore_vec_we0,
        restore_vec_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] t_13;
input  [30:0] m;
input  [13:0] zext_ln258;
input  [13:0] add_ln260;
output  [13:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;
output  [4:0] cur_cfwd_address0;
output   cur_cfwd_ce0;
input  [15:0] cur_cfwd_q0;
output  [4:0] cur_cfwd_address1;
output   cur_cfwd_ce1;
output   cur_cfwd_we1;
output  [15:0] cur_cfwd_d1;
output  [4:0] rem_r_address0;
output   rem_r_ce0;
input  [31:0] rem_r_q0;
output  [4:0] rem_r_address1;
output   rem_r_ce1;
output   rem_r_we1;
output  [31:0] rem_r_d1;
output  [7:0] t_18_out;
output   t_18_out_ap_vld;
output  [13:0] restore_vec_address0;
output   restore_vec_ce0;
output   restore_vec_we0;
output  [15:0] restore_vec_d0;

reg ap_idle;
reg p_ce0;
reg cur_cfwd_ce0;
reg cur_cfwd_ce1;
reg cur_cfwd_we1;
reg rem_r_ce0;
reg rem_r_ce1;
reg rem_r_we1;
reg t_18_out_ap_vld;
reg restore_vec_ce0;
reg restore_vec_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln254_fu_203_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln254_reg_366;
reg   [0:0] icmp_ln254_reg_366_pp0_iter1_reg;
wire   [13:0] add_ln258_fu_225_p2;
reg   [13:0] add_ln258_reg_370;
reg   [4:0] cur_cfwd_addr_reg_380;
reg   [4:0] cur_cfwd_addr_reg_380_pp0_iter1_reg;
reg   [4:0] cur_cfwd_addr_reg_380_pp0_iter2_reg;
reg   [4:0] rem_addr_reg_386;
reg   [4:0] rem_addr_reg_386_pp0_iter1_reg;
reg   [15:0] old_cf_reg_392;
reg   [15:0] pj_reg_397;
reg   [15:0] tmp_reg_403;
wire   [15:0] add_ln29_fu_301_p2;
reg   [15:0] add_ln29_reg_408;
wire   [63:0] zext_ln260_fu_237_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln254_fu_215_p1;
wire   [63:0] zext_ln258_2_fu_247_p1;
reg   [7:0] t_fu_78;
wire   [7:0] t_10_fu_319_p3;
wire    ap_loop_init;
reg   [31:0] prev_fu_82;
wire   [31:0] prev_1_fu_285_p2;
reg   [5:0] k_3_fu_86;
reg   [5:0] ap_sig_allocacmp_k;
wire   [5:0] add_ln254_fu_209_p2;
wire    ap_block_pp0_stage0_01001;
wire   [30:0] zext_ln254_1_fu_199_p1;
wire   [13:0] zext_ln258_1_fu_221_p1;
wire   [13:0] add_ln260_1_fu_231_p2;
wire   [31:0] zext_ln262_fu_254_p1;
wire   [31:0] zext_ln265_fu_264_p1;
wire   [0:0] icmp_ln265_fu_267_p2;
wire   [31:0] base_fu_273_p3;
wire   [15:0] trunc_ln269_fu_281_p1;
wire   [0:0] icmp_ln22_fu_314_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_35;
reg    ap_enable_state1_pp0_iter0_stage0;
wire    ap_enable_operation_41;
reg    ap_enable_state2_pp0_iter1_stage0;
wire    ap_enable_operation_64;
reg    ap_enable_state4_pp0_iter3_stage0;
wire    ap_enable_operation_44;
wire    ap_enable_operation_47;
reg    ap_enable_state3_pp0_iter2_stage0;
wire    ap_enable_operation_49;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln254_fu_203_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            k_3_fu_86 <= add_ln254_fu_209_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_3_fu_86 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            prev_fu_82 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            prev_fu_82 <= prev_1_fu_285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            t_fu_78 <= t_13;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            t_fu_78 <= t_10_fu_319_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln254_fu_203_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln258_reg_370 <= add_ln258_fu_225_p2;
        cur_cfwd_addr_reg_380 <= zext_ln254_fu_215_p1;
        rem_addr_reg_386 <= zext_ln254_fu_215_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln29_reg_408 <= add_ln29_fu_301_p2;
        cur_cfwd_addr_reg_380_pp0_iter2_reg <= cur_cfwd_addr_reg_380_pp0_iter1_reg;
        tmp_reg_403 <= {{prev_1_fu_285_p2[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cur_cfwd_addr_reg_380_pp0_iter1_reg <= cur_cfwd_addr_reg_380;
        icmp_ln254_reg_366 <= icmp_ln254_fu_203_p2;
        icmp_ln254_reg_366_pp0_iter1_reg <= icmp_ln254_reg_366;
        pj_reg_397 <= p_q0;
        rem_addr_reg_386_pp0_iter1_reg <= rem_addr_reg_386;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        old_cf_reg_392 <= cur_cfwd_q0;
    end
end

always @ (*) begin
    if (((icmp_ln254_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k = 6'd0;
    end else begin
        ap_sig_allocacmp_k = k_3_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cfwd_ce0 = 1'b1;
    end else begin
        cur_cfwd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        cur_cfwd_ce1 = 1'b1;
    end else begin
        cur_cfwd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        cur_cfwd_we1 = 1'b1;
    end else begin
        cur_cfwd_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rem_r_ce0 = 1'b1;
    end else begin
        rem_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rem_r_ce1 = 1'b1;
    end else begin
        rem_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rem_r_we1 = 1'b1;
    end else begin
        rem_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        restore_vec_ce0 = 1'b1;
    end else begin
        restore_vec_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        restore_vec_we0 = 1'b1;
    end else begin
        restore_vec_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln254_reg_366_pp0_iter1_reg == 1'd1))) begin
        t_18_out_ap_vld = 1'b1;
    end else begin
        t_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln254_fu_209_p2 = (ap_sig_allocacmp_k + 6'd1);

assign add_ln258_fu_225_p2 = (zext_ln258 + zext_ln258_1_fu_221_p1);

assign add_ln260_1_fu_231_p2 = (add_ln260 + zext_ln258_1_fu_221_p1);

assign add_ln29_fu_301_p2 = (pj_reg_397 + trunc_ln269_fu_281_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_35 = (icmp_ln254_fu_203_p2 == 1'd0);
end

assign ap_enable_operation_41 = (1'b1 == 1'b1);

assign ap_enable_operation_44 = (1'b1 == 1'b1);

assign ap_enable_operation_47 = (1'b1 == 1'b1);

assign ap_enable_operation_49 = (1'b1 == 1'b1);

assign ap_enable_operation_64 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign base_fu_273_p3 = ((icmp_ln265_fu_267_p2[0:0] == 1'b1) ? zext_ln265_fu_264_p1 : prev_fu_82);

assign cur_cfwd_address0 = zext_ln254_fu_215_p1;

assign cur_cfwd_address1 = cur_cfwd_addr_reg_380_pp0_iter2_reg;

assign cur_cfwd_d1 = ((icmp_ln22_fu_314_p2[0:0] == 1'b1) ? 16'd65535 : add_ln29_reg_408);

assign icmp_ln22_fu_314_p2 = ((tmp_reg_403 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln254_fu_203_p2 = ((zext_ln254_1_fu_199_p1 == m) ? 1'b1 : 1'b0);

assign icmp_ln265_fu_267_p2 = ((zext_ln265_fu_264_p1 > prev_fu_82) ? 1'b1 : 1'b0);

assign p_address0 = zext_ln260_fu_237_p1;

assign prev_1_fu_285_p2 = (base_fu_273_p3 + zext_ln262_fu_254_p1);

assign rem_r_address0 = rem_addr_reg_386;

assign rem_r_address1 = rem_addr_reg_386_pp0_iter1_reg;

assign rem_r_d1 = (rem_r_q0 - zext_ln262_fu_254_p1);

assign restore_vec_address0 = zext_ln258_2_fu_247_p1;

assign restore_vec_d0 = cur_cfwd_q0;

assign t_10_fu_319_p3 = ((icmp_ln22_fu_314_p2[0:0] == 1'b1) ? 8'd1 : t_fu_78);

assign t_18_out = t_fu_78;

assign trunc_ln269_fu_281_p1 = base_fu_273_p3[15:0];

assign zext_ln254_1_fu_199_p1 = ap_sig_allocacmp_k;

assign zext_ln254_fu_215_p1 = ap_sig_allocacmp_k;

assign zext_ln258_1_fu_221_p1 = ap_sig_allocacmp_k;

assign zext_ln258_2_fu_247_p1 = add_ln258_reg_370;

assign zext_ln260_fu_237_p1 = add_ln260_1_fu_231_p2;

assign zext_ln262_fu_254_p1 = pj_reg_397;

assign zext_ln265_fu_264_p1 = old_cf_reg_392;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_254_8
