// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_527_17 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add_ln316,
        t_5,
        t_6,
        t_12,
        t_sroa_52_7_lcssa43107120147163,
        empty,
        use_fwd_3109119149161,
        sel_tmp6,
        phi_ln59,
        active_depth_3,
        sp_4_out,
        sp_4_out_ap_vld,
        t_44_out,
        t_44_out_ap_vld,
        t_43_out,
        t_43_out_ap_vld,
        t_42_out,
        t_42_out_ap_vld,
        t_41_out,
        t_41_out_ap_vld,
        f_surv_tokens_1_address0,
        f_surv_tokens_1_ce0,
        f_surv_tokens_1_q0,
        f_surv_tokens_0_address0,
        f_surv_tokens_0_ce0,
        f_surv_tokens_0_q0,
        b_surv_tokens_1_address0,
        b_surv_tokens_1_ce0,
        b_surv_tokens_1_q0,
        b_surv_tokens_0_address0,
        b_surv_tokens_0_ce0,
        b_surv_tokens_0_q0,
        frontier_stack_address0,
        frontier_stack_ce0,
        frontier_stack_we0,
        frontier_stack_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] add_ln316;
input  [31:0] t_5;
input  [31:0] t_6;
input  [63:0] t_12;
input  [7:0] t_sroa_52_7_lcssa43107120147163;
input  [31:0] empty;
input  [0:0] use_fwd_3109119149161;
input  [0:0] sel_tmp6;
input  [9:0] phi_ln59;
input  [8:0] active_depth_3;
output  [31:0] sp_4_out;
output   sp_4_out_ap_vld;
output  [31:0] t_44_out;
output   t_44_out_ap_vld;
output  [31:0] t_43_out;
output   t_43_out_ap_vld;
output  [63:0] t_42_out;
output   t_42_out_ap_vld;
output  [7:0] t_41_out;
output   t_41_out_ap_vld;
output  [7:0] f_surv_tokens_1_address0;
output   f_surv_tokens_1_ce0;
input  [31:0] f_surv_tokens_1_q0;
output  [7:0] f_surv_tokens_0_address0;
output   f_surv_tokens_0_ce0;
input  [31:0] f_surv_tokens_0_q0;
output  [7:0] b_surv_tokens_1_address0;
output   b_surv_tokens_1_ce0;
input  [31:0] b_surv_tokens_1_q0;
output  [7:0] b_surv_tokens_0_address0;
output   b_surv_tokens_0_ce0;
input  [31:0] b_surv_tokens_0_q0;
output  [10:0] frontier_stack_address0;
output   frontier_stack_ce0;
output   frontier_stack_we0;
output  [19:0] frontier_stack_d0;

reg ap_idle;
reg sp_4_out_ap_vld;
reg t_44_out_ap_vld;
reg t_43_out_ap_vld;
reg t_42_out_ap_vld;
reg t_41_out_ap_vld;
reg f_surv_tokens_1_ce0;
reg f_surv_tokens_0_ce0;
reg b_surv_tokens_1_ce0;
reg b_surv_tokens_0_ce0;
reg frontier_stack_ce0;
reg frontier_stack_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln527_fu_323_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln527_reg_610;
wire   [0:0] trunc_ln532_fu_335_p1;
reg   [0:0] trunc_ln532_reg_614;
reg   [31:0] sp_load_1_reg_641;
wire   [0:0] icmp_ln538_fu_428_p2;
reg   [0:0] icmp_ln538_reg_646;
wire   [9:0] or_ln61_fu_453_p2;
reg   [9:0] or_ln61_reg_650;
wire   [31:0] sp_1_fu_458_p2;
reg   [31:0] sp_1_reg_655;
wire   [63:0] zext_ln532_fu_349_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln540_fu_503_p1;
reg   [31:0] idx_fu_106;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_idx_1;
wire   [31:0] add_ln527_fu_329_p2;
reg   [7:0] t_fu_110;
reg   [63:0] t_1_fu_114;
wire   [63:0] t_4_fu_464_p2;
reg   [31:0] t_2_fu_118;
wire   [31:0] t_8_fu_512_p3;
reg   [31:0] t_3_fu_122;
wire   [31:0] t_7_fu_470_p2;
reg   [31:0] sp_fu_126;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] lshr_ln9_fu_339_p4;
wire   [0:0] xor_ln532_fu_365_p2;
wire   [0:0] and_ln533_fu_375_p2;
wire   [8:0] trunc_ln536_fu_379_p1;
wire   [8:0] trunc_ln536_1_fu_383_p1;
wire   [0:0] and_ln532_fu_370_p2;
wire   [8:0] trunc_ln536_2_fu_395_p1;
wire   [8:0] trunc_ln536_3_fu_399_p1;
wire   [8:0] select_ln533_fu_387_p3;
wire   [8:0] select_ln533_1_fu_403_p3;
wire   [20:0] tmp_1_fu_418_p4;
wire   [8:0] tok_fu_411_p3;
wire   [9:0] tmp_s_fu_445_p3;
wire   [0:0] icmp_ln552_fu_507_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln527_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            idx_fu_106 <= add_ln527_fu_329_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_106 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sp_fu_126 <= add_ln316;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln538_fu_428_p2 == 1'd1))) begin
            sp_fu_126 <= sp_1_fu_458_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_1_fu_114 <= t_12;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln538_fu_428_p2 == 1'd1))) begin
            t_1_fu_114 <= t_4_fu_464_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            t_2_fu_118 <= t_6;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln538_reg_646 == 1'd1))) begin
            t_2_fu_118 <= t_8_fu_512_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_3_fu_122 <= t_5;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln538_fu_428_p2 == 1'd1))) begin
            t_3_fu_122 <= t_7_fu_470_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_fu_110 <= t_sroa_52_7_lcssa43107120147163;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln538_fu_428_p2 == 1'd0))) begin
            t_fu_110 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln527_reg_610 <= icmp_ln527_fu_323_p2;
        icmp_ln538_reg_646 <= icmp_ln538_fu_428_p2;
        sp_load_1_reg_641 <= sp_fu_126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln538_fu_428_p2 == 1'd1))) begin
        or_ln61_reg_650 <= or_ln61_fu_453_p2;
        sp_1_reg_655 <= sp_1_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln527_fu_323_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln532_reg_614 <= trunc_ln532_fu_335_p1;
    end
end

always @ (*) begin
    if (((icmp_ln527_fu_323_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_idx_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_idx_1 = idx_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_surv_tokens_0_ce0 = 1'b1;
    end else begin
        b_surv_tokens_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_surv_tokens_1_ce0 = 1'b1;
    end else begin
        b_surv_tokens_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        f_surv_tokens_0_ce0 = 1'b1;
    end else begin
        f_surv_tokens_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        f_surv_tokens_1_ce0 = 1'b1;
    end else begin
        f_surv_tokens_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        frontier_stack_ce0 = 1'b1;
    end else begin
        frontier_stack_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln538_reg_646 == 1'd1))) begin
        frontier_stack_we0 = 1'b1;
    end else begin
        frontier_stack_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln527_reg_610 == 1'd1))) begin
        sp_4_out_ap_vld = 1'b1;
    end else begin
        sp_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln527_reg_610 == 1'd1))) begin
        t_41_out_ap_vld = 1'b1;
    end else begin
        t_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln527_reg_610 == 1'd1))) begin
        t_42_out_ap_vld = 1'b1;
    end else begin
        t_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln527_reg_610 == 1'd1))) begin
        t_43_out_ap_vld = 1'b1;
    end else begin
        t_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln527_reg_610 == 1'd1))) begin
        t_44_out_ap_vld = 1'b1;
    end else begin
        t_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln527_fu_329_p2 = (ap_sig_allocacmp_idx_1 + 32'd1);

assign and_ln532_fu_370_p2 = (xor_ln532_fu_365_p2 & use_fwd_3109119149161);

assign and_ln533_fu_375_p2 = (trunc_ln532_reg_614 & sel_tmp6);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_surv_tokens_0_address0 = zext_ln532_fu_349_p1;

assign b_surv_tokens_1_address0 = zext_ln532_fu_349_p1;

assign f_surv_tokens_0_address0 = zext_ln532_fu_349_p1;

assign f_surv_tokens_1_address0 = zext_ln532_fu_349_p1;

assign frontier_stack_address0 = zext_ln540_fu_503_p1;

assign frontier_stack_d0 = {{{active_depth_3}, {1'd0}}, {or_ln61_reg_650}};

assign icmp_ln527_fu_323_p2 = ((ap_sig_allocacmp_idx_1 == empty) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_428_p2 = (($signed(tmp_1_fu_418_p4) < $signed(21'd1)) ? 1'b1 : 1'b0);

assign icmp_ln552_fu_507_p2 = ((sp_1_reg_655 > t_2_fu_118) ? 1'b1 : 1'b0);

assign lshr_ln9_fu_339_p4 = {{ap_sig_allocacmp_idx_1[8:1]}};

assign or_ln61_fu_453_p2 = (tmp_s_fu_445_p3 | phi_ln59);

assign select_ln533_1_fu_403_p3 = ((and_ln532_fu_370_p2[0:0] == 1'b1) ? trunc_ln536_2_fu_395_p1 : trunc_ln536_3_fu_399_p1);

assign select_ln533_fu_387_p3 = ((and_ln533_fu_375_p2[0:0] == 1'b1) ? trunc_ln536_fu_379_p1 : trunc_ln536_1_fu_383_p1);

assign sp_1_fu_458_p2 = (sp_fu_126 + 32'd1);

assign sp_4_out = sp_fu_126;

assign t_41_out = t_fu_110;

assign t_42_out = t_1_fu_114;

assign t_43_out = t_2_fu_118;

assign t_44_out = t_3_fu_122;

assign t_4_fu_464_p2 = (t_1_fu_114 + 64'd19);

assign t_7_fu_470_p2 = (t_3_fu_122 + 32'd1);

assign t_8_fu_512_p3 = ((icmp_ln552_fu_507_p2[0:0] == 1'b1) ? sp_1_reg_655 : t_2_fu_118);

assign tmp_1_fu_418_p4 = {{sp_fu_126[31:11]}};

assign tmp_s_fu_445_p3 = {{1'd0}, {tok_fu_411_p3}};

assign tok_fu_411_p3 = ((trunc_ln532_reg_614[0:0] == 1'b1) ? select_ln533_fu_387_p3 : select_ln533_1_fu_403_p3);

assign trunc_ln532_fu_335_p1 = ap_sig_allocacmp_idx_1[0:0];

assign trunc_ln536_1_fu_383_p1 = f_surv_tokens_1_q0[8:0];

assign trunc_ln536_2_fu_395_p1 = f_surv_tokens_0_q0[8:0];

assign trunc_ln536_3_fu_399_p1 = b_surv_tokens_0_q0[8:0];

assign trunc_ln536_fu_379_p1 = b_surv_tokens_1_q0[8:0];

assign xor_ln532_fu_365_p2 = (trunc_ln532_reg_614 ^ 1'd1);

assign zext_ln532_fu_349_p1 = lshr_ln9_fu_339_p4;

assign zext_ln540_fu_503_p1 = sp_load_1_reg_641;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_527_17
