// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_143_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m,
        cur_cfwd_address1,
        cur_cfwd_ce1,
        cur_cfwd_we1,
        cur_cfwd_d1,
        cur_cbwd_address1,
        cur_cbwd_ce1,
        cur_cbwd_we1,
        cur_cbwd_d1,
        rem_r_address1,
        rem_r_ce1,
        rem_r_we1,
        rem_r_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m;
output  [4:0] cur_cfwd_address1;
output   cur_cfwd_ce1;
output   cur_cfwd_we1;
output  [15:0] cur_cfwd_d1;
output  [4:0] cur_cbwd_address1;
output   cur_cbwd_ce1;
output   cur_cbwd_we1;
output  [15:0] cur_cbwd_d1;
output  [4:0] rem_r_address1;
output   rem_r_ce1;
output   rem_r_we1;
output  [31:0] rem_r_d1;

reg ap_idle;
reg cur_cfwd_ce1;
reg cur_cfwd_we1;
reg cur_cbwd_ce1;
reg cur_cbwd_we1;
reg rem_r_ce1;
reg rem_r_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln143_fu_114_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln143_fu_126_p1;
reg   [5:0] k_fu_38;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_k_4;
wire   [5:0] add_ln143_fu_120_p2;
wire   [31:0] zext_ln143_1_fu_110_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln143_fu_114_p2 == 1'd0)) begin
            k_fu_38 <= add_ln143_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_38 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_114_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_k_4 = 6'd0;
    end else begin
        ap_sig_allocacmp_k_4 = k_fu_38;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        cur_cbwd_ce1 = 1'b1;
    end else begin
        cur_cbwd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        cur_cbwd_we1 = 1'b1;
    end else begin
        cur_cbwd_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        cur_cfwd_ce1 = 1'b1;
    end else begin
        cur_cfwd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        cur_cfwd_we1 = 1'b1;
    end else begin
        cur_cfwd_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        rem_r_ce1 = 1'b1;
    end else begin
        rem_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        rem_r_we1 = 1'b1;
    end else begin
        rem_r_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln143_fu_120_p2 = (ap_sig_allocacmp_k_4 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cur_cbwd_address1 = zext_ln143_fu_126_p1;

assign cur_cbwd_d1 = 16'd0;

assign cur_cfwd_address1 = zext_ln143_fu_126_p1;

assign cur_cfwd_d1 = 16'd0;

assign icmp_ln143_fu_114_p2 = ((zext_ln143_1_fu_110_p1 == m) ? 1'b1 : 1'b0);

assign rem_r_address1 = zext_ln143_fu_126_p1;

assign rem_r_d1 = 32'd0;

assign zext_ln143_1_fu_110_p1 = ap_sig_allocacmp_k_4;

assign zext_ln143_fu_126_p1 = ap_sig_allocacmp_k_4;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_143_2
