// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_385_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln167,
        add_ln335,
        p_address0,
        p_ce0,
        p_q0,
        cur_cfwd_address0,
        cur_cfwd_ce0,
        cur_cfwd_q0,
        cur_cbwd_address0,
        cur_cbwd_ce0,
        cur_cbwd_q0,
        rem_r_address0,
        rem_r_ce0,
        rem_r_q0,
        lb_b_out,
        lb_b_out_ap_vld,
        c_run_b_out,
        c_run_b_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sext_ln167;
input  [13:0] add_ln335;
output  [13:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;
output  [4:0] cur_cfwd_address0;
output   cur_cfwd_ce0;
input  [15:0] cur_cfwd_q0;
output  [4:0] cur_cbwd_address0;
output   cur_cbwd_ce0;
input  [15:0] cur_cbwd_q0;
output  [4:0] rem_r_address0;
output   rem_r_ce0;
input  [31:0] rem_r_q0;
output  [31:0] lb_b_out;
output   lb_b_out_ap_vld;
output  [31:0] c_run_b_out;
output   c_run_b_out_ap_vld;

reg ap_idle;
reg p_ce0;
reg cur_cfwd_ce0;
reg cur_cbwd_ce0;
reg rem_r_ce0;
reg lb_b_out_ap_vld;
reg c_run_b_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_183_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] k_1_reg_332;
reg   [63:0] k_1_reg_332_pp0_iter2_reg;
reg   [0:0] tmp_reg_343;
reg   [0:0] tmp_reg_343_pp0_iter2_reg;
reg   [0:0] tmp_reg_343_pp0_iter3_reg;
reg   [15:0] pj_reg_352;
reg   [15:0] cb_parent_reg_357;
wire   [31:0] c_run_b_1_fu_225_p2;
reg   [31:0] c_run_b_1_reg_372;
wire   [31:0] rem_excl_fu_249_p3;
reg   [31:0] rem_excl_reg_377;
wire   [31:0] v_fu_271_p2;
reg   [31:0] v_reg_382;
wire   [63:0] zext_ln388_fu_178_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] c_run_b_fu_56;
wire    ap_loop_init;
reg   [31:0] lb_b_fu_60;
wire   [31:0] lb_b_1_fu_284_p3;
reg   [63:0] k_fu_64;
wire   [63:0] add_ln385_fu_191_p2;
wire  signed [63:0] sext_ln167_cast_fu_146_p1;
wire    ap_block_pp0_stage0_01001;
wire   [13:0] trunc_ln388_fu_169_p1;
wire   [13:0] add_ln388_fu_173_p2;
wire   [31:0] zext_ln394_fu_205_p1;
wire   [0:0] icmp_ln394_fu_208_p2;
wire   [31:0] base_fu_214_p3;
wire   [31:0] zext_ln398_fu_222_p1;
wire   [0:0] icmp_ln401_fu_231_p2;
wire   [0:0] xor_ln401_fu_237_p2;
wire   [31:0] sub_ln402_fu_243_p2;
wire   [31:0] zext_ln406_fu_262_p1;
wire   [31:0] add_ln406_fu_266_p2;
wire   [0:0] icmp_ln408_fu_279_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            c_run_b_fu_56 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            c_run_b_fu_56 <= c_run_b_1_fu_225_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_64 <= sext_ln167_cast_fu_146_p1;
        end else if (((tmp_fu_183_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_64 <= add_ln385_fu_191_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lb_b_fu_60 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            lb_b_fu_60 <= lb_b_1_fu_284_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        k_1_reg_332 <= k_fu_64;
        tmp_reg_343 <= k_fu_64[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        c_run_b_1_reg_372 <= c_run_b_1_fu_225_p2;
        cb_parent_reg_357 <= cur_cbwd_q0;
        k_1_reg_332_pp0_iter2_reg <= k_1_reg_332;
        pj_reg_352 <= p_q0;
        rem_excl_reg_377 <= rem_excl_fu_249_p3;
        tmp_reg_343_pp0_iter2_reg <= tmp_reg_343;
        tmp_reg_343_pp0_iter3_reg <= tmp_reg_343_pp0_iter2_reg;
        v_reg_382 <= v_fu_271_p2;
    end
end

always @ (*) begin
    if (((tmp_fu_183_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_343_pp0_iter3_reg == 1'd1))) begin
        c_run_b_out_ap_vld = 1'b1;
    end else begin
        c_run_b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cbwd_ce0 = 1'b1;
    end else begin
        cur_cbwd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        cur_cfwd_ce0 = 1'b1;
    end else begin
        cur_cfwd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_343_pp0_iter3_reg == 1'd1))) begin
        lb_b_out_ap_vld = 1'b1;
    end else begin
        lb_b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rem_r_ce0 = 1'b1;
    end else begin
        rem_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln385_fu_191_p2 = ($signed(k_fu_64) + $signed(64'd18446744073709551615));

assign add_ln388_fu_173_p2 = (add_ln335 + trunc_ln388_fu_169_p1);

assign add_ln406_fu_266_p2 = (c_run_b_1_reg_372 + zext_ln406_fu_262_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign base_fu_214_p3 = ((icmp_ln394_fu_208_p2[0:0] == 1'b1) ? zext_ln394_fu_205_p1 : c_run_b_fu_56);

assign c_run_b_1_fu_225_p2 = (base_fu_214_p3 + zext_ln398_fu_222_p1);

assign c_run_b_out = c_run_b_fu_56;

assign cur_cbwd_address0 = k_fu_64;

assign cur_cfwd_address0 = k_1_reg_332_pp0_iter2_reg;

assign icmp_ln394_fu_208_p2 = ((zext_ln394_fu_205_p1 > c_run_b_fu_56) ? 1'b1 : 1'b0);

assign icmp_ln401_fu_231_p2 = ((rem_r_q0 < zext_ln398_fu_222_p1) ? 1'b1 : 1'b0);

assign icmp_ln408_fu_279_p2 = ((v_reg_382 > lb_b_fu_60) ? 1'b1 : 1'b0);

assign lb_b_1_fu_284_p3 = ((icmp_ln408_fu_279_p2[0:0] == 1'b1) ? v_reg_382 : lb_b_fu_60);

assign lb_b_out = lb_b_fu_60;

assign p_address0 = zext_ln388_fu_178_p1;

assign rem_excl_fu_249_p3 = ((xor_ln401_fu_237_p2[0:0] == 1'b1) ? sub_ln402_fu_243_p2 : 32'd0);

assign rem_r_address0 = k_1_reg_332;

assign sext_ln167_cast_fu_146_p1 = $signed(sext_ln167);

assign sub_ln402_fu_243_p2 = (rem_r_q0 - zext_ln398_fu_222_p1);

assign tmp_fu_183_p3 = k_fu_64[32'd63];

assign trunc_ln388_fu_169_p1 = k_fu_64[13:0];

assign v_fu_271_p2 = (add_ln406_fu_266_p2 + rem_excl_reg_377);

assign xor_ln401_fu_237_p2 = (icmp_ln401_fu_231_p2 ^ 1'd1);

assign zext_ln388_fu_178_p1 = add_ln388_fu_173_p2;

assign zext_ln394_fu_205_p1 = cb_parent_reg_357;

assign zext_ln398_fu_222_p1 = pj_reg_352;

assign zext_ln406_fu_262_p1 = cur_cfwd_q0;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_385_12
