// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_508_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln501,
        key,
        pos_out,
        pos_out_ap_vld,
        b_surv_tokens_1_address0,
        b_surv_tokens_1_ce0,
        b_surv_tokens_1_q0,
        b_surv_tokens_1_address1,
        b_surv_tokens_1_ce1,
        b_surv_tokens_1_we1,
        b_surv_tokens_1_d1,
        b_surv_tokens_0_address0,
        b_surv_tokens_0_ce0,
        b_surv_tokens_0_q0,
        b_surv_tokens_0_address1,
        b_surv_tokens_0_ce1,
        b_surv_tokens_0_we1,
        b_surv_tokens_0_d1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] zext_ln501;
input  [31:0] key;
output  [8:0] pos_out;
output   pos_out_ap_vld;
output  [7:0] b_surv_tokens_1_address0;
output   b_surv_tokens_1_ce0;
input  [31:0] b_surv_tokens_1_q0;
output  [7:0] b_surv_tokens_1_address1;
output   b_surv_tokens_1_ce1;
output   b_surv_tokens_1_we1;
output  [31:0] b_surv_tokens_1_d1;
output  [7:0] b_surv_tokens_0_address0;
output   b_surv_tokens_0_ce0;
input  [31:0] b_surv_tokens_0_q0;
output  [7:0] b_surv_tokens_0_address1;
output   b_surv_tokens_0_ce1;
output   b_surv_tokens_0_we1;
output  [31:0] b_surv_tokens_0_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pos_out_ap_vld;
reg b_surv_tokens_1_ce0;
reg b_surv_tokens_1_ce1;
reg b_surv_tokens_1_we1;
reg b_surv_tokens_0_ce0;
reg b_surv_tokens_0_ce1;
reg b_surv_tokens_0_we1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] pos_1_reg_224;
wire    ap_CS_fsm_state2;
wire   [8:0] trunc_ln509_fu_135_p1;
reg   [8:0] trunc_ln509_reg_230;
reg   [0:0] tmp_reg_236;
wire   [63:0] zext_ln510_fu_157_p1;
wire   [63:0] zext_ln513_fu_196_p1;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln510_fu_176_p2;
reg   [63:0] pos_fu_50;
wire   [63:0] add_ln516_fu_202_p2;
wire   [63:0] zext_ln501_cast_fu_123_p1;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] trunc_ln510_fu_163_p1;
wire   [31:0] select_ln510_fu_166_p3;
wire   [7:0] lshr_ln3_fu_147_p4;
wire   [8:0] add_ln513_fu_181_p2;
wire   [7:0] lshr_ln7_fu_186_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pos_fu_50 <= zext_ln501_cast_fu_123_p1;
    end else if (((icmp_ln510_fu_176_p2 == 1'd1) & (tmp_reg_236 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        pos_fu_50 <= add_ln516_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pos_1_reg_224 <= pos_fu_50;
        tmp_reg_236 <= pos_fu_50[32'd63];
        trunc_ln509_reg_230 <= trunc_ln509_fu_135_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_surv_tokens_0_ce0 = 1'b1;
    end else begin
        b_surv_tokens_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        b_surv_tokens_0_ce1 = 1'b1;
    end else begin
        b_surv_tokens_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln510_fu_176_p2 == 1'd1) & (tmp_reg_236 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln510_fu_163_p1 == 1'd1))) begin
        b_surv_tokens_0_we1 = 1'b1;
    end else begin
        b_surv_tokens_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_surv_tokens_1_ce0 = 1'b1;
    end else begin
        b_surv_tokens_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        b_surv_tokens_1_ce1 = 1'b1;
    end else begin
        b_surv_tokens_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln510_fu_176_p2 == 1'd1) & (tmp_reg_236 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln510_fu_163_p1 == 1'd0))) begin
        b_surv_tokens_1_we1 = 1'b1;
    end else begin
        b_surv_tokens_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((tmp_reg_236 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        pos_out_ap_vld = 1'b1;
    end else begin
        pos_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln510_fu_176_p2 == 1'd1) & (tmp_reg_236 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((tmp_reg_236 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln513_fu_181_p2 = (trunc_ln509_reg_230 + 9'd1);

assign add_ln516_fu_202_p2 = ($signed(pos_1_reg_224) + $signed(64'd18446744073709551615));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign b_surv_tokens_0_address0 = zext_ln510_fu_157_p1;

assign b_surv_tokens_0_address1 = zext_ln513_fu_196_p1;

assign b_surv_tokens_0_d1 = select_ln510_fu_166_p3;

assign b_surv_tokens_1_address0 = zext_ln510_fu_157_p1;

assign b_surv_tokens_1_address1 = zext_ln513_fu_196_p1;

assign b_surv_tokens_1_d1 = select_ln510_fu_166_p3;

assign icmp_ln510_fu_176_p2 = ((select_ln510_fu_166_p3 < key) ? 1'b1 : 1'b0);

assign lshr_ln3_fu_147_p4 = {{pos_fu_50[8:1]}};

assign lshr_ln7_fu_186_p4 = {{add_ln513_fu_181_p2[8:1]}};

assign pos_out = trunc_ln509_reg_230;

assign select_ln510_fu_166_p3 = ((trunc_ln510_fu_163_p1[0:0] == 1'b1) ? b_surv_tokens_1_q0 : b_surv_tokens_0_q0);

assign trunc_ln509_fu_135_p1 = pos_fu_50[8:0];

assign trunc_ln510_fu_163_p1 = pos_1_reg_224[0:0];

assign zext_ln501_cast_fu_123_p1 = zext_ln501;

assign zext_ln510_fu_157_p1 = lshr_ln3_fu_147_p4;

assign zext_ln513_fu_196_p1 = lshr_ln7_fu_186_p4;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_508_16
