// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_213_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m,
        rem_r_address0,
        rem_r_ce0,
        rem_r_q0,
        rem_r_address1,
        rem_r_ce1,
        rem_r_we1,
        rem_r_d1,
        cur_cfwd_address1,
        cur_cfwd_ce1,
        cur_cfwd_we1,
        cur_cfwd_d1,
        zext_ln216,
        add_ln224_1,
        p_address0,
        p_ce0,
        p_q0,
        undo_fwd,
        cur_cbwd_address1,
        cur_cbwd_ce1,
        cur_cbwd_we1,
        cur_cbwd_d1,
        restore_vec_address0,
        restore_vec_ce0,
        restore_vec_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m;
output  [4:0] rem_r_address0;
output   rem_r_ce0;
input  [31:0] rem_r_q0;
output  [4:0] rem_r_address1;
output   rem_r_ce1;
output   rem_r_we1;
output  [31:0] rem_r_d1;
output  [4:0] cur_cfwd_address1;
output   cur_cfwd_ce1;
output   cur_cfwd_we1;
output  [15:0] cur_cfwd_d1;
input  [13:0] zext_ln216;
input  [13:0] add_ln224_1;
output  [13:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;
input  [0:0] undo_fwd;
output  [4:0] cur_cbwd_address1;
output   cur_cbwd_ce1;
output   cur_cbwd_we1;
output  [15:0] cur_cbwd_d1;
output  [13:0] restore_vec_address0;
output   restore_vec_ce0;
input  [15:0] restore_vec_q0;

reg ap_idle;
reg rem_r_ce0;
reg rem_r_ce1;
reg rem_r_we1;
reg cur_cfwd_ce1;
reg cur_cfwd_we1;
reg p_ce0;
reg cur_cbwd_ce1;
reg cur_cbwd_we1;
reg restore_vec_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln213_fu_181_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] undo_fwd_read_reg_247;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] k_reg_251;
reg   [15:0] p_load_reg_270;
reg   [4:0] rem_addr_reg_275;
wire   [63:0] zext_ln216_2_fu_203_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln224_1_fu_214_p1;
wire   [63:0] zext_ln213_fu_224_p1;
reg   [5:0] k_2_fu_62;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_k;
wire   [5:0] add_ln213_fu_187_p2;
wire   [31:0] zext_ln213_1_fu_177_p1;
wire   [13:0] zext_ln216_1_fu_193_p1;
wire   [13:0] add_ln216_fu_197_p2;
wire   [13:0] add_ln224_2_fu_208_p2;
wire   [31:0] zext_ln224_fu_230_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
wire    ap_enable_operation_47;
reg    ap_enable_state2_pp0_iter1_stage0;
wire    ap_enable_operation_49;
reg    ap_enable_state3_pp0_iter2_stage0;
wire    ap_enable_operation_51;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_2_fu_62 <= add_ln213_fu_187_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_2_fu_62 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        k_reg_251 <= ap_sig_allocacmp_k;
        p_load_reg_270 <= p_q0;
        rem_addr_reg_275 <= zext_ln213_fu_224_p1;
    end
end

always @ (*) begin
    if (((icmp_ln213_fu_181_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k = 6'd0;
    end else begin
        ap_sig_allocacmp_k = k_2_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cbwd_ce1 = 1'b1;
    end else begin
        cur_cbwd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((undo_fwd_read_reg_247 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cbwd_we1 = 1'b1;
    end else begin
        cur_cbwd_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cfwd_ce1 = 1'b1;
    end else begin
        cur_cfwd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((undo_fwd_read_reg_247 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cfwd_we1 = 1'b1;
    end else begin
        cur_cfwd_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rem_r_ce0 = 1'b1;
    end else begin
        rem_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rem_r_ce1 = 1'b1;
    end else begin
        rem_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rem_r_we1 = 1'b1;
    end else begin
        rem_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        restore_vec_ce0 = 1'b1;
    end else begin
        restore_vec_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln213_fu_187_p2 = (ap_sig_allocacmp_k + 6'd1);

assign add_ln216_fu_197_p2 = (zext_ln216 + zext_ln216_1_fu_193_p1);

assign add_ln224_2_fu_208_p2 = (add_ln224_1 + zext_ln216_1_fu_193_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_operation_47 = (1'b1 == 1'b1);

assign ap_enable_operation_49 = (1'b1 == 1'b1);

assign ap_enable_operation_51 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cur_cbwd_address1 = zext_ln213_fu_224_p1;

assign cur_cbwd_d1 = restore_vec_q0;

assign cur_cfwd_address1 = zext_ln213_fu_224_p1;

assign cur_cfwd_d1 = restore_vec_q0;

assign icmp_ln213_fu_181_p2 = ((zext_ln213_1_fu_177_p1 == m) ? 1'b1 : 1'b0);

assign p_address0 = zext_ln224_1_fu_214_p1;

assign rem_r_address0 = zext_ln213_fu_224_p1;

assign rem_r_address1 = rem_addr_reg_275;

assign rem_r_d1 = (rem_r_q0 + zext_ln224_fu_230_p1);

assign restore_vec_address0 = zext_ln216_2_fu_203_p1;

assign undo_fwd_read_reg_247 = undo_fwd;

assign zext_ln213_1_fu_177_p1 = ap_sig_allocacmp_k;

assign zext_ln213_fu_224_p1 = k_reg_251;

assign zext_ln216_1_fu_193_p1 = ap_sig_allocacmp_k;

assign zext_ln216_2_fu_203_p1 = add_ln216_fu_197_p2;

assign zext_ln224_1_fu_214_p1 = add_ln224_2_fu_208_p2;

assign zext_ln224_fu_230_p1 = p_load_reg_270;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_213_7
