// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_150_3_VITIS_LOOP_151_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m,
        mul_ln150,
        p_address0,
        p_ce0,
        p_q0,
        rem_r_address0,
        rem_r_ce0,
        rem_r_q0,
        rem_r_address1,
        rem_r_ce1,
        rem_r_we1,
        rem_r_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m;
input  [63:0] mul_ln150;
output  [13:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;
output  [4:0] rem_r_address0;
output   rem_r_ce0;
input  [31:0] rem_r_q0;
output  [4:0] rem_r_address1;
output   rem_r_ce1;
output   rem_r_we1;
output  [31:0] rem_r_d1;

reg ap_idle;
reg p_ce0;
reg rem_r_ce0;
reg rem_r_ce1;
reg rem_r_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln150_fu_147_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln150_fu_167_p3;
reg   [5:0] select_ln150_reg_291;
wire   [9:0] select_ln150_1_fu_175_p3;
reg   [9:0] select_ln150_1_reg_297;
reg   [4:0] rem_addr_reg_308;
reg   [4:0] rem_addr_reg_308_pp0_iter3_reg;
reg   [15:0] p_load_reg_314;
wire   [63:0] zext_ln153_3_fu_241_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln151_fu_228_p1;
reg   [5:0] k_1_fu_64;
wire   [5:0] add_ln151_fu_183_p2;
wire    ap_loop_init;
reg   [9:0] j_fu_68;
reg   [63:0] indvar_flatten_fu_72;
wire   [63:0] add_ln150_1_fu_152_p2;
wire   [31:0] zext_ln151_1_fu_138_p1;
wire   [0:0] icmp_ln151_fu_142_p2;
wire   [9:0] add_ln150_fu_161_p2;
wire   [11:0] tmp_1_fu_211_p3;
wire   [13:0] tmp_fu_204_p3;
wire   [13:0] zext_ln153_1_fu_218_p1;
wire   [13:0] add_ln153_1_fu_222_p2;
wire   [13:0] zext_ln153_2_fu_232_p1;
wire   [13:0] add_ln153_2_fu_235_p2;
wire   [31:0] zext_ln153_fu_246_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
wire    ap_enable_operation_45;
reg    ap_enable_state4_pp0_iter3_stage0;
wire    ap_enable_operation_51;
reg    ap_enable_state5_pp0_iter4_stage0;
wire    ap_enable_operation_53;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_72 <= 64'd0;
        end else if (((icmp_ln150_fu_147_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_72 <= add_ln150_1_fu_152_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_68 <= 10'd0;
        end else if (((icmp_ln150_fu_147_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_68 <= select_ln150_1_fu_175_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_1_fu_64 <= 6'd0;
        end else if (((icmp_ln150_fu_147_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_1_fu_64 <= add_ln151_fu_183_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        p_load_reg_314 <= p_q0;
        rem_addr_reg_308 <= zext_ln151_fu_228_p1;
        rem_addr_reg_308_pp0_iter3_reg <= rem_addr_reg_308;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln150_fu_147_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln150_1_reg_297 <= select_ln150_1_fu_175_p3;
        select_ln150_reg_291 <= select_ln150_fu_167_p3;
    end
end

always @ (*) begin
    if (((icmp_ln150_fu_147_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rem_r_ce0 = 1'b1;
    end else begin
        rem_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        rem_r_ce1 = 1'b1;
    end else begin
        rem_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        rem_r_we1 = 1'b1;
    end else begin
        rem_r_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln150_1_fu_152_p2 = (indvar_flatten_fu_72 + 64'd1);

assign add_ln150_fu_161_p2 = (j_fu_68 + 10'd1);

assign add_ln151_fu_183_p2 = (select_ln150_fu_167_p3 + 6'd1);

assign add_ln153_1_fu_222_p2 = (tmp_fu_204_p3 + zext_ln153_1_fu_218_p1);

assign add_ln153_2_fu_235_p2 = (add_ln153_1_fu_222_p2 + zext_ln153_2_fu_232_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_operation_45 = (1'b1 == 1'b1);

assign ap_enable_operation_51 = (1'b1 == 1'b1);

assign ap_enable_operation_53 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln150_fu_147_p2 = ((indvar_flatten_fu_72 == mul_ln150) ? 1'b1 : 1'b0);

assign icmp_ln151_fu_142_p2 = ((zext_ln151_1_fu_138_p1 == m) ? 1'b1 : 1'b0);

assign p_address0 = zext_ln153_3_fu_241_p1;

assign rem_r_address0 = rem_addr_reg_308;

assign rem_r_address1 = rem_addr_reg_308_pp0_iter3_reg;

assign rem_r_d1 = (rem_r_q0 + zext_ln153_fu_246_p1);

assign select_ln150_1_fu_175_p3 = ((icmp_ln151_fu_142_p2[0:0] == 1'b1) ? add_ln150_fu_161_p2 : j_fu_68);

assign select_ln150_fu_167_p3 = ((icmp_ln151_fu_142_p2[0:0] == 1'b1) ? 6'd0 : k_1_fu_64);

assign tmp_1_fu_211_p3 = {{select_ln150_1_reg_297}, {2'd0}};

assign tmp_fu_204_p3 = {{select_ln150_1_reg_297}, {4'd0}};

assign zext_ln151_1_fu_138_p1 = k_1_fu_64;

assign zext_ln151_fu_228_p1 = select_ln150_reg_291;

assign zext_ln153_1_fu_218_p1 = tmp_1_fu_211_p3;

assign zext_ln153_2_fu_232_p1 = select_ln150_reg_291;

assign zext_ln153_3_fu_241_p1 = add_ln153_2_fu_235_p2;

assign zext_ln153_fu_246_p1 = p_load_reg_314;

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_150_3_VITIS_LOOP_151_4
