// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_332_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m,
        add_ln335,
        p_address0,
        p_ce0,
        p_q0,
        cur_cfwd_address0,
        cur_cfwd_ce0,
        cur_cfwd_q0,
        cur_cbwd_address0,
        cur_cbwd_ce0,
        cur_cbwd_q0,
        rem_r_address0,
        rem_r_ce0,
        rem_r_q0,
        lb_f_out,
        lb_f_out_ap_vld,
        c_run_f_out,
        c_run_f_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m;
input  [13:0] add_ln335;
output  [13:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;
output  [4:0] cur_cfwd_address0;
output   cur_cfwd_ce0;
input  [15:0] cur_cfwd_q0;
output  [4:0] cur_cbwd_address0;
output   cur_cbwd_ce0;
input  [15:0] cur_cbwd_q0;
output  [4:0] rem_r_address0;
output   rem_r_ce0;
input  [31:0] rem_r_q0;
output  [31:0] lb_f_out;
output   lb_f_out_ap_vld;
output  [31:0] c_run_f_out;
output   c_run_f_out_ap_vld;

reg ap_idle;
reg p_ce0;
reg cur_cfwd_ce0;
reg cur_cbwd_ce0;
reg rem_r_ce0;
reg lb_f_out_ap_vld;
reg c_run_f_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln332_fu_172_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln332_reg_334;
reg   [0:0] icmp_ln332_reg_334_pp0_iter1_reg;
reg   [0:0] icmp_ln332_reg_334_pp0_iter2_reg;
wire   [63:0] zext_ln332_1_fu_184_p1;
reg   [63:0] zext_ln332_1_reg_338;
reg   [63:0] zext_ln332_1_reg_338_pp0_iter1_reg;
reg   [15:0] pj_reg_354;
reg   [15:0] cf_parent_reg_359;
wire   [31:0] c_run_f_1_fu_232_p2;
reg   [31:0] c_run_f_1_reg_374;
wire   [31:0] rem_excl_fu_256_p3;
reg   [31:0] rem_excl_reg_379;
wire   [31:0] v_fu_278_p2;
reg   [31:0] v_reg_384;
wire   [63:0] zext_ln335_1_fu_199_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] c_run_f_fu_60;
wire    ap_loop_init;
reg   [31:0] lb_f_fu_64;
wire   [31:0] lb_f_1_fu_291_p3;
reg   [5:0] k_fu_68;
reg   [5:0] ap_sig_allocacmp_k_2;
wire   [5:0] add_ln332_fu_178_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln332_fu_168_p1;
wire   [13:0] zext_ln335_fu_189_p1;
wire   [13:0] add_ln335_1_fu_193_p2;
wire   [31:0] zext_ln341_fu_212_p1;
wire   [0:0] icmp_ln341_fu_215_p2;
wire   [31:0] base_fu_221_p3;
wire   [31:0] zext_ln345_fu_229_p1;
wire   [0:0] icmp_ln348_fu_238_p2;
wire   [0:0] xor_ln348_fu_244_p2;
wire   [31:0] sub_ln349_fu_250_p2;
wire   [31:0] zext_ln353_fu_269_p1;
wire   [31:0] add_ln353_fu_273_p2;
wire   [0:0] icmp_ln355_fu_286_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fd_bb_slbb_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            c_run_f_fu_60 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            c_run_f_fu_60 <= c_run_f_1_fu_232_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln332_fu_172_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_68 <= add_ln332_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_68 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lb_f_fu_64 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            lb_f_fu_64 <= lb_f_1_fu_291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cf_parent_reg_359 <= cur_cfwd_q0;
        icmp_ln332_reg_334 <= icmp_ln332_fu_172_p2;
        icmp_ln332_reg_334_pp0_iter1_reg <= icmp_ln332_reg_334;
        pj_reg_354 <= p_q0;
        zext_ln332_1_reg_338_pp0_iter1_reg[5 : 0] <= zext_ln332_1_reg_338[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        c_run_f_1_reg_374 <= c_run_f_1_fu_232_p2;
        icmp_ln332_reg_334_pp0_iter2_reg <= icmp_ln332_reg_334_pp0_iter1_reg;
        rem_excl_reg_379 <= rem_excl_fu_256_p3;
        v_reg_384 <= v_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln332_fu_172_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln332_1_reg_338[5 : 0] <= zext_ln332_1_fu_184_p1[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln332_fu_172_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln332_reg_334_pp0_iter2_reg == 1'd1))) begin
        c_run_f_out_ap_vld = 1'b1;
    end else begin
        c_run_f_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cur_cbwd_ce0 = 1'b1;
    end else begin
        cur_cbwd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_cfwd_ce0 = 1'b1;
    end else begin
        cur_cfwd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln332_reg_334_pp0_iter2_reg == 1'd1))) begin
        lb_f_out_ap_vld = 1'b1;
    end else begin
        lb_f_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rem_r_ce0 = 1'b1;
    end else begin
        rem_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln332_fu_178_p2 = (ap_sig_allocacmp_k_2 + 6'd1);

assign add_ln335_1_fu_193_p2 = (add_ln335 + zext_ln335_fu_189_p1);

assign add_ln353_fu_273_p2 = (rem_excl_reg_379 + zext_ln353_fu_269_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign base_fu_221_p3 = ((icmp_ln341_fu_215_p2[0:0] == 1'b1) ? zext_ln341_fu_212_p1 : c_run_f_fu_60);

assign c_run_f_1_fu_232_p2 = (base_fu_221_p3 + zext_ln345_fu_229_p1);

assign c_run_f_out = c_run_f_fu_60;

assign cur_cbwd_address0 = zext_ln332_1_reg_338_pp0_iter1_reg;

assign cur_cfwd_address0 = zext_ln332_1_fu_184_p1;

assign icmp_ln332_fu_172_p2 = ((zext_ln332_fu_168_p1 == m) ? 1'b1 : 1'b0);

assign icmp_ln341_fu_215_p2 = ((zext_ln341_fu_212_p1 > c_run_f_fu_60) ? 1'b1 : 1'b0);

assign icmp_ln348_fu_238_p2 = ((rem_r_q0 < zext_ln345_fu_229_p1) ? 1'b1 : 1'b0);

assign icmp_ln355_fu_286_p2 = ((v_reg_384 > lb_f_fu_64) ? 1'b1 : 1'b0);

assign lb_f_1_fu_291_p3 = ((icmp_ln355_fu_286_p2[0:0] == 1'b1) ? v_reg_384 : lb_f_fu_64);

assign lb_f_out = lb_f_fu_64;

assign p_address0 = zext_ln335_1_fu_199_p1;

assign rem_excl_fu_256_p3 = ((xor_ln348_fu_244_p2[0:0] == 1'b1) ? sub_ln349_fu_250_p2 : 32'd0);

assign rem_r_address0 = zext_ln332_1_reg_338;

assign sub_ln349_fu_250_p2 = (rem_r_q0 - zext_ln345_fu_229_p1);

assign v_fu_278_p2 = (add_ln353_fu_273_p2 + c_run_f_1_reg_374);

assign xor_ln348_fu_244_p2 = (icmp_ln348_fu_238_p2 ^ 1'd1);

assign zext_ln332_1_fu_184_p1 = ap_sig_allocacmp_k_2;

assign zext_ln332_fu_168_p1 = ap_sig_allocacmp_k_2;

assign zext_ln335_1_fu_199_p1 = add_ln335_1_fu_193_p2;

assign zext_ln335_fu_189_p1 = ap_sig_allocacmp_k_2;

assign zext_ln341_fu_212_p1 = cf_parent_reg_359;

assign zext_ln345_fu_229_p1 = pj_reg_354;

assign zext_ln353_fu_269_p1 = cur_cbwd_q0;

always @ (posedge ap_clk) begin
    zext_ln332_1_reg_338[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln332_1_reg_338_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //fd_bb_slbb_fd_bb_slbb_Pipeline_VITIS_LOOP_332_11
